<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: payments.proto

namespace Payments\Services\Grpc;

use Mix\Grpc;
use Mix\Grpc\Context;

interface PaymentsServiceInterface extends Grpc\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "payments.services.grpc.PaymentsService";

    /**
    * @param Context $context
    * @param Id $request
    * @return Invoice
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function getInvoiceById(Context $context, Id $request): Invoice;

    /**
    * @param Context $context
    * @param Invoice $request
    * @return Invoice
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function pay(Context $context, Invoice $request): Invoice;

    /**
    * @param Context $context
    * @param EmptyObject $request
    * @return PaymentCurrencies
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function getPaymentCurrencies(Context $context, EmptyObject $request): PaymentCurrencies;

    /**
    * @param Context $context
    * @param EmptyObject $request
    * @return PaymentTypes
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function getPaymentTypes(Context $context, EmptyObject $request): PaymentTypes;
}
