<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: orders.proto

namespace Orders\Services;


use Orders\Services\Grpc\Id;
use Orders\Services\Grpc\Order;

interface OrdersServiceInterface
{
    public function OrderById(Id $request): Order;

    public function updateOrder(Order $order): Order;
}
