<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: orders.proto

namespace Orders\Services;


interface OrdersServiceInterface
{
    public function OrderById(Id $request): Order;
}
