<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: orders.proto

namespace Orders\Services;

use Mix\Grpc;
use Mix\Grpc\Context;

class OrdersServiceClient extends Grpc\Client\AbstractClient
{
    /**
    * @param Context $context
    * @param Id $request
    * @param array $options
    * @return Order
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function OrderById(Context $context, Id $request): Order
    {
        return $this->_simpleRequest('/orders.services.OrdersService/OrderById', $context, $request, new Order());
    }
}
