<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

namespace Orders\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>orders.services.Order</code>
 */
class Order extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>int64 to_user_id = 3;</code>
     */
    protected $to_user_id = 0;
    /**
     * Generated from protobuf field <code>int64 total_cost_in_usd = 4;</code>
     */
    protected $total_cost_in_usd = 0;
    /**
     * Generated from protobuf field <code>int64 packages_cost_in_usd = 5;</code>
     */
    protected $packages_cost_in_usd = 0;
    /**
     * Generated from protobuf field <code>int64 registration_fee_in_usd = 6;</code>
     */
    protected $registration_fee_in_usd = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp is_paid_at = 7;</code>
     */
    protected $is_paid_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp is_resolved_at = 8;</code>
     */
    protected $is_resolved_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp is_refund_at = 9;</code>
     */
    protected $is_refund_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp is_expired_at = 10;</code>
     */
    protected $is_expired_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp is_commission_resolved_at = 11;</code>
     */
    protected $is_commission_resolved_at = null;
    /**
     * Generated from protobuf field <code>string payment_type = 12;</code>
     */
    protected $payment_type = '';
    /**
     * Generated from protobuf field <code>string payment_currency = 13;</code>
     */
    protected $payment_currency = '';
    /**
     * Generated from protobuf field <code>string payment_driver = 14;</code>
     */
    protected $payment_driver = '';
    /**
     * Generated from protobuf field <code>string plan = 15;</code>
     */
    protected $plan = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp deleted_at = 16;</code>
     */
    protected $deleted_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 17;</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 18;</code>
     */
    protected $updated_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $user_id
     *     @type int|string $to_user_id
     *     @type int|string $total_cost_in_usd
     *     @type int|string $packages_cost_in_usd
     *     @type int|string $registration_fee_in_usd
     *     @type \Google\Protobuf\Timestamp $is_paid_at
     *     @type \Google\Protobuf\Timestamp $is_resolved_at
     *     @type \Google\Protobuf\Timestamp $is_refund_at
     *     @type \Google\Protobuf\Timestamp $is_expired_at
     *     @type \Google\Protobuf\Timestamp $is_commission_resolved_at
     *     @type string $payment_type
     *     @type string $payment_currency
     *     @type string $payment_driver
     *     @type string $plan
     *     @type \Google\Protobuf\Timestamp $deleted_at
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $updated_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Orders::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 to_user_id = 3;</code>
     * @return int|string
     */
    public function getToUserId()
    {
        return $this->to_user_id;
    }

    /**
     * Generated from protobuf field <code>int64 to_user_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setToUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->to_user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total_cost_in_usd = 4;</code>
     * @return int|string
     */
    public function getTotalCostInUsd()
    {
        return $this->total_cost_in_usd;
    }

    /**
     * Generated from protobuf field <code>int64 total_cost_in_usd = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalCostInUsd($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_cost_in_usd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 packages_cost_in_usd = 5;</code>
     * @return int|string
     */
    public function getPackagesCostInUsd()
    {
        return $this->packages_cost_in_usd;
    }

    /**
     * Generated from protobuf field <code>int64 packages_cost_in_usd = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPackagesCostInUsd($var)
    {
        GPBUtil::checkInt64($var);
        $this->packages_cost_in_usd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 registration_fee_in_usd = 6;</code>
     * @return int|string
     */
    public function getRegistrationFeeInUsd()
    {
        return $this->registration_fee_in_usd;
    }

    /**
     * Generated from protobuf field <code>int64 registration_fee_in_usd = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRegistrationFeeInUsd($var)
    {
        GPBUtil::checkInt64($var);
        $this->registration_fee_in_usd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp is_paid_at = 7;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getIsPaidAt()
    {
        return $this->is_paid_at;
    }

    public function hasIsPaidAt()
    {
        return isset($this->is_paid_at);
    }

    public function clearIsPaidAt()
    {
        unset($this->is_paid_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp is_paid_at = 7;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setIsPaidAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->is_paid_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp is_resolved_at = 8;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getIsResolvedAt()
    {
        return $this->is_resolved_at;
    }

    public function hasIsResolvedAt()
    {
        return isset($this->is_resolved_at);
    }

    public function clearIsResolvedAt()
    {
        unset($this->is_resolved_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp is_resolved_at = 8;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setIsResolvedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->is_resolved_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp is_refund_at = 9;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getIsRefundAt()
    {
        return $this->is_refund_at;
    }

    public function hasIsRefundAt()
    {
        return isset($this->is_refund_at);
    }

    public function clearIsRefundAt()
    {
        unset($this->is_refund_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp is_refund_at = 9;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setIsRefundAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->is_refund_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp is_expired_at = 10;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getIsExpiredAt()
    {
        return $this->is_expired_at;
    }

    public function hasIsExpiredAt()
    {
        return isset($this->is_expired_at);
    }

    public function clearIsExpiredAt()
    {
        unset($this->is_expired_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp is_expired_at = 10;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setIsExpiredAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->is_expired_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp is_commission_resolved_at = 11;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getIsCommissionResolvedAt()
    {
        return $this->is_commission_resolved_at;
    }

    public function hasIsCommissionResolvedAt()
    {
        return isset($this->is_commission_resolved_at);
    }

    public function clearIsCommissionResolvedAt()
    {
        unset($this->is_commission_resolved_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp is_commission_resolved_at = 11;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setIsCommissionResolvedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->is_commission_resolved_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payment_type = 12;</code>
     * @return string
     */
    public function getPaymentType()
    {
        return $this->payment_type;
    }

    /**
     * Generated from protobuf field <code>string payment_type = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payment_currency = 13;</code>
     * @return string
     */
    public function getPaymentCurrency()
    {
        return $this->payment_currency;
    }

    /**
     * Generated from protobuf field <code>string payment_currency = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payment_driver = 14;</code>
     * @return string
     */
    public function getPaymentDriver()
    {
        return $this->payment_driver;
    }

    /**
     * Generated from protobuf field <code>string payment_driver = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentDriver($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_driver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string plan = 15;</code>
     * @return string
     */
    public function getPlan()
    {
        return $this->plan;
    }

    /**
     * Generated from protobuf field <code>string plan = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setPlan($var)
    {
        GPBUtil::checkString($var, True);
        $this->plan = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp deleted_at = 16;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getDeletedAt()
    {
        return $this->deleted_at;
    }

    public function hasDeletedAt()
    {
        return isset($this->deleted_at);
    }

    public function clearDeletedAt()
    {
        unset($this->deleted_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp deleted_at = 16;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setDeletedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->deleted_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 17;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 17;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 18;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 18;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

}

