<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Á

user.protouser.services"Þ
User

id (

first_name (	
	last_name (	
username (	
email (	
role (	
	member_id (

sponsor_id (

block_type	 (	
	is_freeze
 (
is_deactivate (
is_fake (";

UserUpdate

id (
to_id (

queue_name (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

