<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
à

user.protouser.services"º
User

id (

first_name (	
	last_name (	
username (	
email (	
role (	

sponsor_id (

block_type (	
	is_freeze	 (
is_deactivate
 (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

