<?php

const ORDER_PAYMENT_TYPE_GIFT_CODE = 'ORDER_PAYMENT_TYPE_GIFT_CODE';
const ORDER_PAYMENT_TYPE_BITCOIN = 'ORDER_PAYMENT_TYPE_BITCOIN';
const ORDER_PAYMENT_TYPE_WALLET = 'ORDER_PAYMENT_TYPE_WALLET';
const ORDER_PAYMENT_TYPES = [
    ORDER_PAYMENT_TYPE_GIFT_CODE,
    ORDER_PAYMENT_TYPE_BITCOIN,
    ORDER_PAYMENT_TYPE_WALLET
];

const ORDER_PLAN_DEFAULT = 'ORDER_PLAN_DEFAULT';
const ORDER_PLANS = [
    ORDER_PLAN_DEFAULT
];

if (!function_exists('example')) {

    function example()
    {

    }
}
