<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packages.proto

namespace Packages\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>packages.services.IndirectCommission</code>
 */
class IndirectCommission extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 level = 1;</code>
     */
    protected $level = 0;
    /**
     * Generated from protobuf field <code>int32 percentage = 2;</code>
     */
    protected $percentage = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $level
     *     @type int $percentage
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Packages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 level = 1;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>int32 level = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 percentage = 2;</code>
     * @return int
     */
    public function getPercentage()
    {
        return $this->percentage;
    }

    /**
     * Generated from protobuf field <code>int32 percentage = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPercentage($var)
    {
        GPBUtil::checkInt32($var);
        $this->percentage = $var;

        return $this;
    }

}

