<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: packages.proto

namespace Packages\Services;

interface PackagesServiceInterface
{
    public function packageById(Id $request): Package;
}
