<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: packages.proto

namespace Packages\Services;

use Packages\Services\Grpc\Id;
use Packages\Services\Grpc\Package;

interface PackagesServiceInterface
{
    public function packageById(Id $request): Package;

    public function packageFullById(Id $request): Package;
}
