<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: packages.proto

namespace Packages\Services;

use Mix\Grpc;
use Mix\Grpc\Context;

class PackagesServiceClient extends Grpc\Client\AbstractClient
{
    /**
    * @param Context $context
    * @param Id $request
    * @param array $options
    * @return Package
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function packageById(Context $context, Id $request): Package
    {
        return $this->_simpleRequest('/packages.services.PackagesService/packageById', $context, $request, new Package());
    }
}
