<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallets.proto

namespace Wallets\Services\Grpc;

use UnexpectedValueException;

/**
 * Protobuf type <code>wallets.services.grpc.WalletNames</code>
 */
class WalletNames
{
    /**
     * Generated from protobuf enum <code>EARNING = 0;</code>
     */
    const EARNING = 0;
    /**
     * Generated from protobuf enum <code>DEPOSIT = 1;</code>
     */
    const DEPOSIT = 1;
    /**
     * Generated from protobuf enum <code>JANEX = 2;</code>
     */
    const JANEX = 2;

    private static $valueToName = [
        self::EARNING => 'EARNING',
        self::DEPOSIT => 'DEPOSIT',
        self::JANEX => 'JANEX',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

