<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: wallets.proto

namespace Wallets\Services\Grpc;

use Mix\Grpc;
use Mix\Grpc\Context;

interface WalletServiceInterface extends Grpc\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "wallets.services.grpc.WalletService";

    /**
    * @param Context $context
    * @param Deposit $request
    * @return Deposit
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function deposit(Context $context, Deposit $request): Deposit;

    /**
    * @param Context $context
    * @param Withdraw $request
    * @return Withdraw
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function withdraw(Context $context, Withdraw $request): Withdraw;

    /**
    * @param Context $context
    * @param Transfer $request
    * @return Transfer
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function transfer(Context $context, Transfer $request): Transfer;

    /**
    * @param Context $context
    * @param Wallet $request
    * @return Wallet
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function getBalance(Context $context, Wallet $request): Wallet;
}
