<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: giftcodes.proto

namespace Giftcode\Services\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>giftcode.services.grpc.GiftcodesArray</code>
 */
class GiftcodesArray extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .giftcode.services.grpc.Giftcode giftcode = 1;</code>
     */
    private $giftcode;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Giftcode\Services\Grpc\Giftcode[]|\Google\Protobuf\Internal\RepeatedField $giftcode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Giftcodes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .giftcode.services.grpc.Giftcode giftcode = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGiftcode()
    {
        return $this->giftcode;
    }

    /**
     * Generated from protobuf field <code>repeated .giftcode.services.grpc.Giftcode giftcode = 1;</code>
     * @param \Giftcode\Services\Grpc\Giftcode[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGiftcode($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Giftcode\Services\Grpc\Giftcode::class);
        $this->giftcode = $arr;

        return $this;
    }

}

