<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: giftcodes.proto

namespace Giftcode\Services\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>giftcode.services.grpc.Package</code>
 */
class Package extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string short_name = 3;</code>
     */
    protected $short_name = '';
    /**
     * Generated from protobuf field <code>int64 validity_in_days = 4;</code>
     */
    protected $validity_in_days = 0;
    /**
     * Generated from protobuf field <code>int64 price = 5;</code>
     */
    protected $price = 0;
    /**
     * Generated from protobuf field <code>string deleted_at = 6;</code>
     */
    protected $deleted_at = '';
    /**
     * Generated from protobuf field <code>string created_at = 7;</code>
     */
    protected $created_at = '';
    /**
     * Generated from protobuf field <code>string updated_at = 8;</code>
     */
    protected $updated_at = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $name
     *     @type string $short_name
     *     @type int|string $validity_in_days
     *     @type int|string $price
     *     @type string $deleted_at
     *     @type string $created_at
     *     @type string $updated_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Giftcodes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string short_name = 3;</code>
     * @return string
     */
    public function getShortName()
    {
        return $this->short_name;
    }

    /**
     * Generated from protobuf field <code>string short_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setShortName($var)
    {
        GPBUtil::checkString($var, True);
        $this->short_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 validity_in_days = 4;</code>
     * @return int|string
     */
    public function getValidityInDays()
    {
        return $this->validity_in_days;
    }

    /**
     * Generated from protobuf field <code>int64 validity_in_days = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setValidityInDays($var)
    {
        GPBUtil::checkInt64($var);
        $this->validity_in_days = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 price = 5;</code>
     * @return int|string
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>int64 price = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkInt64($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string deleted_at = 6;</code>
     * @return string
     */
    public function getDeletedAt()
    {
        return $this->deleted_at;
    }

    /**
     * Generated from protobuf field <code>string deleted_at = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDeletedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->deleted_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 7;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 8;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updated_at = $var;

        return $this;
    }

}

