<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mlm.proto

namespace MLM\Services\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MLM.services.grpc.PackageRoi</code>
 */
class PackageRoi extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 package_id = 1;</code>
     */
    protected $package_id = 0;
    /**
     * Generated from protobuf field <code>double roi_percentage = 2;</code>
     */
    protected $roi_percentage = 0.0;
    /**
     * Generated from protobuf field <code>string due_date = 3;</code>
     */
    protected $due_date = '';
    /**
     * Generated from protobuf field <code>int64 user_id = 4;</code>
     */
    protected $user_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $package_id
     *     @type float $roi_percentage
     *     @type string $due_date
     *     @type int|string $user_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mlm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 package_id = 1;</code>
     * @return int|string
     */
    public function getPackageId()
    {
        return $this->package_id;
    }

    /**
     * Generated from protobuf field <code>int64 package_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPackageId($var)
    {
        GPBUtil::checkInt64($var);
        $this->package_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double roi_percentage = 2;</code>
     * @return float
     */
    public function getRoiPercentage()
    {
        return $this->roi_percentage;
    }

    /**
     * Generated from protobuf field <code>double roi_percentage = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setRoiPercentage($var)
    {
        GPBUtil::checkDouble($var);
        $this->roi_percentage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string due_date = 3;</code>
     * @return string
     */
    public function getDueDate()
    {
        return $this->due_date;
    }

    /**
     * Generated from protobuf field <code>string due_date = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDueDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->due_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 4;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

}

