<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mlm.proto

namespace MLM\Services\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MLM.services.grpc.Rank</code>
 */
class Rank extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 rank = 1;</code>
     */
    protected $rank = 0;
    /**
     * Generated from protobuf field <code>string rank_name = 2;</code>
     */
    protected $rank_name = '';
    /**
     * Generated from protobuf field <code>int64 condition_converted_in_bp = 3;</code>
     */
    protected $condition_converted_in_bp = 0;
    /**
     * Generated from protobuf field <code>int64 condition_sub_rank = 4;</code>
     */
    protected $condition_sub_rank = 0;
    /**
     * Generated from protobuf field <code>bool condition_direct_or_indirect = 5;</code>
     */
    protected $condition_direct_or_indirect = false;
    /**
     * Generated from protobuf field <code>int64 prize_in_pf = 6;</code>
     */
    protected $prize_in_pf = 0;
    /**
     * Generated from protobuf field <code>string prize_alternative = 7;</code>
     */
    protected $prize_alternative = '';
    /**
     * Generated from protobuf field <code>int64 cap = 8;</code>
     */
    protected $cap = 0;
    /**
     * Generated from protobuf field <code>int64 withdrawal_limit = 9;</code>
     */
    protected $withdrawal_limit = 0;
    /**
     * Generated from protobuf field <code>int64 condition_number_of_left_children = 10;</code>
     */
    protected $condition_number_of_left_children = 0;
    /**
     * Generated from protobuf field <code>int64 condition_number_of_right_children = 11;</code>
     */
    protected $condition_number_of_right_children = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $rank
     *     @type string $rank_name
     *     @type int|string $condition_converted_in_bp
     *     @type int|string $condition_sub_rank
     *     @type bool $condition_direct_or_indirect
     *     @type int|string $prize_in_pf
     *     @type string $prize_alternative
     *     @type int|string $cap
     *     @type int|string $withdrawal_limit
     *     @type int|string $condition_number_of_left_children
     *     @type int|string $condition_number_of_right_children
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Mlm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 rank = 1;</code>
     * @return int|string
     */
    public function getRank()
    {
        return $this->rank;
    }

    /**
     * Generated from protobuf field <code>int64 rank = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRank($var)
    {
        GPBUtil::checkInt64($var);
        $this->rank = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rank_name = 2;</code>
     * @return string
     */
    public function getRankName()
    {
        return $this->rank_name;
    }

    /**
     * Generated from protobuf field <code>string rank_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRankName($var)
    {
        GPBUtil::checkString($var, True);
        $this->rank_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 condition_converted_in_bp = 3;</code>
     * @return int|string
     */
    public function getConditionConvertedInBp()
    {
        return $this->condition_converted_in_bp;
    }

    /**
     * Generated from protobuf field <code>int64 condition_converted_in_bp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConditionConvertedInBp($var)
    {
        GPBUtil::checkInt64($var);
        $this->condition_converted_in_bp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 condition_sub_rank = 4;</code>
     * @return int|string
     */
    public function getConditionSubRank()
    {
        return $this->condition_sub_rank;
    }

    /**
     * Generated from protobuf field <code>int64 condition_sub_rank = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConditionSubRank($var)
    {
        GPBUtil::checkInt64($var);
        $this->condition_sub_rank = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool condition_direct_or_indirect = 5;</code>
     * @return bool
     */
    public function getConditionDirectOrIndirect()
    {
        return $this->condition_direct_or_indirect;
    }

    /**
     * Generated from protobuf field <code>bool condition_direct_or_indirect = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setConditionDirectOrIndirect($var)
    {
        GPBUtil::checkBool($var);
        $this->condition_direct_or_indirect = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 prize_in_pf = 6;</code>
     * @return int|string
     */
    public function getPrizeInPf()
    {
        return $this->prize_in_pf;
    }

    /**
     * Generated from protobuf field <code>int64 prize_in_pf = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPrizeInPf($var)
    {
        GPBUtil::checkInt64($var);
        $this->prize_in_pf = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prize_alternative = 7;</code>
     * @return string
     */
    public function getPrizeAlternative()
    {
        return $this->prize_alternative;
    }

    /**
     * Generated from protobuf field <code>string prize_alternative = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPrizeAlternative($var)
    {
        GPBUtil::checkString($var, True);
        $this->prize_alternative = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 cap = 8;</code>
     * @return int|string
     */
    public function getCap()
    {
        return $this->cap;
    }

    /**
     * Generated from protobuf field <code>int64 cap = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCap($var)
    {
        GPBUtil::checkInt64($var);
        $this->cap = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 withdrawal_limit = 9;</code>
     * @return int|string
     */
    public function getWithdrawalLimit()
    {
        return $this->withdrawal_limit;
    }

    /**
     * Generated from protobuf field <code>int64 withdrawal_limit = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWithdrawalLimit($var)
    {
        GPBUtil::checkInt64($var);
        $this->withdrawal_limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 condition_number_of_left_children = 10;</code>
     * @return int|string
     */
    public function getConditionNumberOfLeftChildren()
    {
        return $this->condition_number_of_left_children;
    }

    /**
     * Generated from protobuf field <code>int64 condition_number_of_left_children = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConditionNumberOfLeftChildren($var)
    {
        GPBUtil::checkInt64($var);
        $this->condition_number_of_left_children = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 condition_number_of_right_children = 11;</code>
     * @return int|string
     */
    public function getConditionNumberOfRightChildren()
    {
        return $this->condition_number_of_right_children;
    }

    /**
     * Generated from protobuf field <code>int64 condition_number_of_right_children = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConditionNumberOfRightChildren($var)
    {
        GPBUtil::checkInt64($var);
        $this->condition_number_of_right_children = $var;

        return $this;
    }

}

