<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: user.proto

namespace User\Services\Grpc;

use Mix\Grpc;
use Mix\Grpc\Context;

interface UserServiceInterface extends Grpc\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "user.services.grpc.UserService";

    /**
    * @param Context $context
    * @param Id $request
    * @return User
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function getUserById(Context $context, Id $request): User;

    /**
    * @param Context $context
    * @param WalletRequest $request
    * @return WalletInfo
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function getUserWalletInfo(Context $context, WalletRequest $request): WalletInfo;
}
