<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace User\Services\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>user.services.grpc.WalletInfo</code>
 */
class WalletInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.user.services.grpc.WalletType wallet_type = 1;</code>
     */
    protected $wallet_type = 0;
    /**
     * Generated from protobuf field <code>string address = 2;</code>
     */
    protected $address = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $wallet_type
     *     @type string $address
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.user.services.grpc.WalletType wallet_type = 1;</code>
     * @return int
     */
    public function getWalletType()
    {
        return $this->wallet_type;
    }

    /**
     * Generated from protobuf field <code>.user.services.grpc.WalletType wallet_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setWalletType($var)
    {
        GPBUtil::checkEnum($var, \User\Services\Grpc\WalletType::class);
        $this->wallet_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 2;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

}

