<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace User\Services\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>user.services.grpc.WalletRequest</code>
 */
class WalletRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>.user.services.grpc.WalletType wallet_type = 2;</code>
     */
    protected $wallet_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user_id
     *     @type int $wallet_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.user.services.grpc.WalletType wallet_type = 2;</code>
     * @return int
     */
    public function getWalletType()
    {
        return $this->wallet_type;
    }

    /**
     * Generated from protobuf field <code>.user.services.grpc.WalletType wallet_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setWalletType($var)
    {
        GPBUtil::checkEnum($var, \User\Services\Grpc\WalletType::class);
        $this->wallet_type = $var;

        return $this;
    }

}

