<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: packages.proto

namespace Packages\Services\Grpc;

use Mix\Grpc;
use Mix\Grpc\Context;

interface PackagesServiceInterface extends Grpc\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "packages.services.grpc.PackagesService";

    /**
    * @param Context $context
    * @param Id $request
    * @return Package
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function packageById(Context $context, Id $request): Package;
}
