<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packages.proto

namespace Packages\Services\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>packages.services.grpc.PackageCheck</code>
 */
class PackageCheck extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 package_index_id = 1;</code>
     */
    protected $package_index_id = 0;
    /**
     * Generated from protobuf field <code>int64 package_to_buy_id = 2;</code>
     */
    protected $package_to_buy_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $package_index_id
     *     @type int|string $package_to_buy_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Packages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 package_index_id = 1;</code>
     * @return int|string
     */
    public function getPackageIndexId()
    {
        return $this->package_index_id;
    }

    /**
     * Generated from protobuf field <code>int64 package_index_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPackageIndexId($var)
    {
        GPBUtil::checkInt64($var);
        $this->package_index_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 package_to_buy_id = 2;</code>
     * @return int|string
     */
    public function getPackageToBuyId()
    {
        return $this->package_to_buy_id;
    }

    /**
     * Generated from protobuf field <code>int64 package_to_buy_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPackageToBuyId($var)
    {
        GPBUtil::checkInt64($var);
        $this->package_to_buy_id = $var;

        return $this;
    }

}

