<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: orders.proto

namespace Orders\Services\Grpc;

use Mix\Grpc;
use Mix\Grpc\Context;

interface OrdersServiceInterface extends Grpc\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "orders.services.grpc.OrdersService";

    /**
    * @param Context $context
    * @param Order $request
    * @return Acknowledge
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function sponsorPackage(Context $context, Order $request): Acknowledge;
}
