<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: orders.proto

namespace Orders\Services\Grpc;

use Mix\Grpc;
use Mix\Grpc\Context;
use User\Services\Grpc;

interface OrdersServiceInterface extends Grpc\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "orders.services.grpc.OrdersService";

    /**
    * @param Context $context
    * @param Id $request
    * @return Order
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function OrderById(Context $context, Id $request): Order;

    /**
    * @param Context $context
    * @param Order $request
    * @return Order
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function updateOrder(Context $context, Order $request): Order;

    /**
    * @param Context $context
    * @param Grpc\User $request
    * @return Order
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function hasValidPackage(Context $context, Grpc\User $request): Order;
}
