<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto

namespace Orders\Services\Grpc;

use UnexpectedValueException;

/**
 * Protobuf type <code>orders.services.grpc.OrderPlans</code>
 */
class OrderPlans
{
    /**
     * Generated from protobuf enum <code>ORDER_PLAN_PURCHASE = 0;</code>
     */
    const ORDER_PLAN_PURCHASE = 0;
    /**
     * Generated from protobuf enum <code>ORDER_PLAN_START = 1;</code>
     */
    const ORDER_PLAN_START = 1;
    /**
     * Generated from protobuf enum <code>ORDER_PLAN_SPECIAL = 2;</code>
     */
    const ORDER_PLAN_SPECIAL = 2;
    /**
     * Generated from protobuf enum <code>ORDER_PLAN_COMPANY = 3;</code>
     */
    const ORDER_PLAN_COMPANY = 3;
    /**
     * Generated from protobuf enum <code>ORDER_PLAN_START_50 = 4;</code>
     */
    const ORDER_PLAN_START_50 = 4;
    /**
     * Generated from protobuf enum <code>ORDER_PLAN_START_75 = 5;</code>
     */
    const ORDER_PLAN_START_75 = 5;

    private static $valueToName = [
        self::ORDER_PLAN_PURCHASE => 'ORDER_PLAN_PURCHASE',
        self::ORDER_PLAN_START => 'ORDER_PLAN_START',
        self::ORDER_PLAN_SPECIAL => 'ORDER_PLAN_SPECIAL',
        self::ORDER_PLAN_COMPANY => 'ORDER_PLAN_COMPANY',
        self::ORDER_PLAN_START_50 => 'ORDER_PLAN_START_50',
        self::ORDER_PLAN_START_75 => 'ORDER_PLAN_START_75',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

