<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallets.proto

namespace Wallets\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wallets.services.Transfer</code>
 */
class Transfer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.user.services.User from_user = 1;</code>
     */
    protected $from_user = null;
    /**
     * Generated from protobuf field <code>.user.services.User to_user = 2;</code>
     */
    protected $to_user = null;
    /**
     * Generated from protobuf field <code>.wallets.services.Transaction transaction = 3;</code>
     */
    protected $transaction = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \User\Services\User $from_user
     *     @type \User\Services\User $to_user
     *     @type \Wallets\Services\Transaction $transaction
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wallets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.user.services.User from_user = 1;</code>
     * @return \User\Services\User|null
     */
    public function getFromUser()
    {
        return $this->from_user;
    }

    public function hasFromUser()
    {
        return isset($this->from_user);
    }

    public function clearFromUser()
    {
        unset($this->from_user);
    }

    /**
     * Generated from protobuf field <code>.user.services.User from_user = 1;</code>
     * @param \User\Services\User $var
     * @return $this
     */
    public function setFromUser($var)
    {
        GPBUtil::checkMessage($var, \User\Services\User::class);
        $this->from_user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.user.services.User to_user = 2;</code>
     * @return \User\Services\User|null
     */
    public function getToUser()
    {
        return $this->to_user;
    }

    public function hasToUser()
    {
        return isset($this->to_user);
    }

    public function clearToUser()
    {
        unset($this->to_user);
    }

    /**
     * Generated from protobuf field <code>.user.services.User to_user = 2;</code>
     * @param \User\Services\User $var
     * @return $this
     */
    public function setToUser($var)
    {
        GPBUtil::checkMessage($var, \User\Services\User::class);
        $this->to_user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.wallets.services.Transaction transaction = 3;</code>
     * @return \Wallets\Services\Transaction|null
     */
    public function getTransaction()
    {
        return $this->transaction;
    }

    public function hasTransaction()
    {
        return isset($this->transaction);
    }

    public function clearTransaction()
    {
        unset($this->transaction);
    }

    /**
     * Generated from protobuf field <code>.wallets.services.Transaction transaction = 3;</code>
     * @param \Wallets\Services\Transaction $var
     * @return $this
     */
    public function setTransaction($var)
    {
        GPBUtil::checkMessage($var, \Wallets\Services\Transaction::class);
        $this->transaction = $var;

        return $this;
    }

}

