<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: wallets.proto

namespace Wallets\Services;
use User\Services;

interface WalletServiceInterface
{
    // GRPC specific service name.
    public const NAME = "wallets.services.WalletService";

    public function deposit( Deposit $request): Transaction;

    public function withdraw( Withdraw $request): Transaction;

    public function transfer( Transfer $request): Transaction;

    public function getBalance( Services\User $request): Wallet;
}
