<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallets.proto

namespace Wallets\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wallets.services.Withdraw</code>
 */
class Withdraw extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.user.services.User user = 1;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>.wallets.services.Transaction transaction = 2;</code>
     */
    protected $transaction = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \User\Services\User $user
     *     @type \Wallets\Services\Transaction $transaction
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wallets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.user.services.User user = 1;</code>
     * @return \User\Services\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.user.services.User user = 1;</code>
     * @param \User\Services\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \User\Services\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.wallets.services.Transaction transaction = 2;</code>
     * @return \Wallets\Services\Transaction|null
     */
    public function getTransaction()
    {
        return $this->transaction;
    }

    public function hasTransaction()
    {
        return isset($this->transaction);
    }

    public function clearTransaction()
    {
        unset($this->transaction);
    }

    /**
     * Generated from protobuf field <code>.wallets.services.Transaction transaction = 2;</code>
     * @param \Wallets\Services\Transaction $var
     * @return $this
     */
    public function setTransaction($var)
    {
        GPBUtil::checkMessage($var, \Wallets\Services\Transaction::class);
        $this->transaction = $var;

        return $this;
    }

}

