<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace User\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>user.services.UserUpdate</code>
 */
class UserUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int64 to_id = 2;</code>
     */
    protected $to_id = 0;
    /**
     * Generated from protobuf field <code>string queue_name = 3;</code>
     */
    protected $queue_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $to_id
     *     @type string $queue_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 to_id = 2;</code>
     * @return int|string
     */
    public function getToId()
    {
        return $this->to_id;
    }

    /**
     * Generated from protobuf field <code>int64 to_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setToId($var)
    {
        GPBUtil::checkInt64($var);
        $this->to_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string queue_name = 3;</code>
     * @return string
     */
    public function getQueueName()
    {
        return $this->queue_name;
    }

    /**
     * Generated from protobuf field <code>string queue_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setQueueName($var)
    {
        GPBUtil::checkString($var, True);
        $this->queue_name = $var;

        return $this;
    }

}

