<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payments.proto

namespace Payments\Services;

if (false) {
    /**
     * This class is deprecated. Use Payments\Services\Invoice\payableType instead.
     * @deprecated
     */
    class Invoice_payableType {}
}
class_exists(Invoice\payableType::class);
@trigger_error('Payments\Services\Invoice_payableType is deprecated and will be removed in the next major release. Use Payments\Services\Invoice\payableType instead', E_USER_DEPRECATED);

