<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payments.proto

namespace Payments\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>payments.services.Invoice</code>
 */
class Invoice extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 order_id = 1;</code>
     */
    protected $order_id = 0;
    /**
     * Generated from protobuf field <code>double amount = 2;</code>
     */
    protected $amount = 0.0;
    /**
     * Generated from protobuf field <code>string transaction_id = 3;</code>
     */
    protected $transaction_id = '';
    /**
     * Generated from protobuf field <code>string checkout_link = 4;</code>
     */
    protected $checkout_link = '';
    /**
     * Generated from protobuf field <code>string status = 5;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>string additional_status = 6;</code>
     */
    protected $additional_status = '';
    /**
     * Generated from protobuf field <code>double paid_amount = 7;</code>
     */
    protected $paid_amount = 0.0;
    /**
     * Generated from protobuf field <code>string deleted_at = 8;</code>
     */
    protected $deleted_at = '';
    /**
     * Generated from protobuf field <code>string created_at = 9;</code>
     */
    protected $created_at = '';
    /**
     * Generated from protobuf field <code>string updated_at = 10;</code>
     */
    protected $updated_at = '';
    /**
     * Generated from protobuf field <code>.orders.services.Order order = 11;</code>
     */
    protected $order = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $order_id
     *     @type float $amount
     *     @type string $transaction_id
     *     @type string $checkout_link
     *     @type string $status
     *     @type string $additional_status
     *     @type float $paid_amount
     *     @type string $deleted_at
     *     @type string $created_at
     *     @type string $updated_at
     *     @type \Orders\Services\Order $order
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Payments::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 order_id = 1;</code>
     * @return int|string
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     * Generated from protobuf field <code>int64 order_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkInt64($var);
        $this->order_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double amount = 2;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>double amount = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string transaction_id = 3;</code>
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * Generated from protobuf field <code>string transaction_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transaction_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string checkout_link = 4;</code>
     * @return string
     */
    public function getCheckoutLink()
    {
        return $this->checkout_link;
    }

    /**
     * Generated from protobuf field <code>string checkout_link = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCheckoutLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->checkout_link = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 5;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string additional_status = 6;</code>
     * @return string
     */
    public function getAdditionalStatus()
    {
        return $this->additional_status;
    }

    /**
     * Generated from protobuf field <code>string additional_status = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAdditionalStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->additional_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double paid_amount = 7;</code>
     * @return float
     */
    public function getPaidAmount()
    {
        return $this->paid_amount;
    }

    /**
     * Generated from protobuf field <code>double paid_amount = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setPaidAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->paid_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string deleted_at = 8;</code>
     * @return string
     */
    public function getDeletedAt()
    {
        return $this->deleted_at;
    }

    /**
     * Generated from protobuf field <code>string deleted_at = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDeletedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->deleted_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 9;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 10;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.orders.services.Order order = 11;</code>
     * @return \Orders\Services\Order|null
     */
    public function getOrder()
    {
        return $this->order;
    }

    public function hasOrder()
    {
        return isset($this->order);
    }

    public function clearOrder()
    {
        unset($this->order);
    }

    /**
     * Generated from protobuf field <code>.orders.services.Order order = 11;</code>
     * @param \Orders\Services\Order $var
     * @return $this
     */
    public function setOrder($var)
    {
        GPBUtil::checkMessage($var, \Orders\Services\Order::class);
        $this->order = $var;

        return $this;
    }

}

