<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: payments.proto

namespace Payments\Services;


interface PaymentsServiceInterface
{
    // GRPC specific service name.
    public const NAME = "payments.services.PaymentsService";


    public function getInvoiceById( Id $request): Invoice;

    public function pay( Invoice $request): Invoice;

    public function getPaymentCurrencies( EmptyObject $request): PaymentCurrencies;

    public function getPaymentTypes( EmptyObject $request): PaymentTypes;
}
