<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: payments.proto

namespace Payments\Services;

use Orders\Services;

interface PaymentsServiceInterface
{
    // GRPC specific service name.

    public function getInvoiceById( Id $request): Invoice;


    public function pay( Services\Order $request): Invoice;


    public function getPaymentCurrencies( EmptyObject $request): PaymentCurrencies;


    public function getPaymentTypes( EmptyObject $request): PaymentTypes;
}
