<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: payments.proto

namespace Payments\Services;

use Mix\Grpc;
use Mix\Grpc\Context;
use Orders\Services;

class PaymentsServiceClient extends Grpc\Client\AbstractClient
{
    /**
    * @param Context $context
    * @param Id $request
    * @param array $options
    * @return Payment
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function paymentById(Context $context, Id $request): Payment
    {
        return $this->_simpleRequest('/payments.services.PaymentsService/paymentById', $context, $request, new Payment());
    }

    /**
    * @param Context $context
    * @param Services\Order $request
    * @param array $options
    * @return Payment
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function pay(Context $context, Services\Order $request): Payment
    {
        return $this->_simpleRequest('/payments.services.PaymentsService/pay', $context, $request, new Payment());
    }

    /**
    * @param Context $context
    * @param Services\Order $request
    * @param array $options
    * @return Payment
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function rollbackPay(Context $context, Services\Order $request): Payment
    {
        return $this->_simpleRequest('/payments.services.PaymentsService/rollbackPay', $context, $request, new Payment());
    }

    /**
    * @param Context $context
    * @param Services\Order $request
    * @param array $options
    * @return Payment
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function refund(Context $context, Services\Order $request): Payment
    {
        return $this->_simpleRequest('/payments.services.PaymentsService/refund', $context, $request, new Payment());
    }

    /**
    * @param Context $context
    * @param Id $request
    * @param array $options
    * @return Payments
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function paymentsByUserId(Context $context, Id $request): Payments
    {
        return $this->_simpleRequest('/payments.services.PaymentsService/paymentsByUserId', $context, $request, new Payments());
    }
}
