<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: payments.proto

namespace Payments\Services;

use Mix\Grpc;
use Mix\Grpc\Context;
use Orders\Services;

class PaymentsServiceClient extends Grpc\Client\AbstractClient
{
    /**
    * @param Context $context
    * @param Services\Order $request
    * @param array $options
    * @return Invoice
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function pay(Context $context, Services\Order $request): Invoice
    {
        return $this->_simpleRequest('/payments.services.PaymentsService/pay', $context, $request, new Invoice());
    }
}
