<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: payments.proto

namespace Payments\Services;

use Mix\Grpc;
use Mix\Grpc\Context;
use Orders\Services;

interface PaymentsServiceInterface extends Grpc\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "payments.services.PaymentsService";

    /**
    * @param Context $context
    * @param Services\Order $request
    * @return Invoice
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function pay(Context $context, Services\Order $request): Invoice;
}
