<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: payments.proto

namespace Payments\Services;


use Payments\Services\Grpc\EmptyObject;
use Payments\Services\Grpc\Id;
use Payments\Services\Grpc\Invoice;
use Payments\Services\Grpc\PaymentTypes;
use Payments\Services\Grpc\PaymentCurrencies;

interface PaymentsServiceInterface
{
    // GRPC specific service name.
    public const NAME = "payments.services.PaymentsService";


    public function getInvoiceById( Id $request): Invoice;

    public function getPaymentCurrencies( EmptyObject $request): PaymentCurrencies;

    public function getPaymentTypes( EmptyObject $request): PaymentTypes;
}
