name: Laravel
on:
  pull_request:
    branches: [ master ]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Config composer
      run: composer config --global --auth http-basic.repo.packagist.com hamid-re3a 9e2c7d6ce623079937fe6dfbfb1ee49e079432ebafec93f3ccd5076aaca0
    - name: Install Dependencies
      run: composer update
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
          username: "root"
          host: "62.171.186.163"
          password: "8BSqG4WVbp9WFr"
          script: "cd /home/staging-subscription/public_html/subscription/ && ./server_deploy.sh"
